backend:
  name: git-gateway
  repo: brunospitti/wedding-rod-mai
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "theme"
    label: "Theme"
    folder: "src/info/theme"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "theme",
        }
      - { label: "Title", name: "title", widget: "string", default: "default" }
      - { label: "primary", name: "primary", widget: "color", allowInput: true, default: "#b27579" }
      - { label: "primaryContrast", name: "primaryContrast", widget: "color", allowInput: true, default: "#ffffff" }
      - { label: "secondary", name: "secondary", widget: "color", allowInput: true, default: "#e4b0b2" }
      - { label: "tertiary", name: "tertiary", widget: "color", allowInput: true, default: "#bda092" }
      - { label: "text", name: "text", widget: "color", allowInput: true, default: "#575d69" }
      - { label: "bg", name: "bg", widget: "color", allowInput: true, default: "#f7f7f7" }

  - name: "banner"
    label: "Banner"
    folder: "src/info/banner"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "banner",
        }
      - { label: "Names", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: false }
      - { label: "Days Left", name: "days-left", widget: "string"}
  
  - name: "welcome"
    label: "Welcome"
    folder: "src/info/welcome"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "welcome",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "sub-title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false}
  
  - name: "invite"
    label: "Invite"
    folder: "src/info/invite"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "invite",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "sub-title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false}
  
  - name: "our-history"
    label: "Our History"
    folder: "src/info/our-history"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "our-history",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "sub-title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false}
  
  - name: "presents"
    label: "Presents"
    folder: "src/info/presents"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "presents",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "sub-title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false}
      - { label: "Button text", name: "button-text", widget: "string" }
      - { label: "Button link", name: "button-link", widget: "string" }
  
  - name: "by-our-side"
    label: "By Our Side"
    folder: "src/info/by-our-side"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "by-our-side",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "sub-title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false}
      - { label: "Parents Title", name: "parents-title", widget: "string" }
      - { label: "Friends Title", name: "friends-title", widget: "string" }
  
  - name: "parents"
    label: "Parents"
    folder: "src/info/parents"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "parents",
        }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Name", name: "title", widget: "string" }
  
  - name: "friends"
    label: "Friends"
    folder: "src/info/friends"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "friends",
        }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Name", name: "title", widget: "string" }
  
  - name: "form"
    label: "Form"
    folder: "src/info/form"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "form",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "sub-title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false}
      - { label: "Name", name: "name", widget: "string" }
      - { label: "E-mail", name: "e-mail", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string" }
      - { label: "Not Going", name: "not-going", widget: "string" }
      - { label: "Maybe", name: "maybe", widget: "string" }
      - { label: "Going", name: "going", widget: "string" }
  
  - name: "finalPhrase"
    label: "Final Phrase"
    folder: "src/info/finalPhrase"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "finalPhrase",
        }
      - { label: "Title", name: "title", widget: "string" }