backend:
  name: git-gateway
  repo: brunospitti/wedding-rod-mai
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "theme"
    label: "Theme"
    folder: "src/info/theme"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "theme",
        }
      - { label: "Title", name: "title", widget: "string", default: "default" }
      - { label: "primary", name: "primary", widget: "color", allowInput: true, default: "#b27579" }
      - { label: "primaryContrast", name: "primaryContrast", widget: "color", allowInput: true, default: "#ffffff" }
      - { label: "secondary", name: "secondary", widget: "color", allowInput: true, default: "#e4b0b2" }
      - { label: "tertiary", name: "tertiary", widget: "color", allowInput: true, default: "#bda092" }
      - { label: "text", name: "text", widget: "color", allowInput: true, default: "#575d69" }
      - { label: "bg", name: "bg", widget: "color", allowInput: true, default: "#f7f7f7" }

  - name: "banner"
    label: "Banner"
    folder: "src/info/banner"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "banner",
        }
      - { label: "Names", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: false }
      - { label: "Days Left", name: "daysLeft", widget: "string"}
  
  - name: "welcome"
    label: "Welcome"
    folder: "src/info/welcome"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "welcome",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "subTitle", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false}
  
  - name: "invite"
    label: "Invite"
    folder: "src/info/invite"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "invite",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "subTitle", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false}
  
  - name: "ourStory"
    label: "Our Story"
    folder: "src/info/ourStory"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "ourStory",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "subTitle", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false}
  
  - name: "presents"
    label: "Presents"
    folder: "src/info/presents"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "presents",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "subTitle", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false}
      - { label: "Button text", name: "buttonText", widget: "string" }
      - { label: "Button link", name: "buttonLink", widget: "string" }
  
  - name: "byOurSide"
    label: "By Our Side"
    folder: "src/info/byOurSide"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "byOurSide",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "subTitle", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false}
      - { label: "Parents Title", name: "parentsTitle", widget: "string" }
      - { label: "Friends Title", name: "friendsTitle", widget: "string" }
  
  - name: "parents"
    label: "Parents"
    folder: "src/info/parents"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "parents",
        }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }
  
  - name: "friends"
    label: "Friends"
    folder: "src/info/friends"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "friends",
        }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }
  
  - name: "form"
    label: "Form"
    folder: "src/info/form"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "form",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "subTitle", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false}
      - { label: "Label - Name", name: "nameLabel", widget: "string" }
      - { label: "Label - e-mail", name: "eMailLabel", widget: "string" }
      - { label: "Label - Phone", name: "phoneLabel", widget: "string" }
      - { label: "Placeholder - Name", name: "namePlaceholder", widget: "string" }
      - { label: "Placeholder - e-mail", name: "eMailPlaceholder", widget: "string" }
      - { label: "Placeholder - Phone", name: "phonePlaceholder", widget: "string" }
      - { label: "Going", name: "going", widget: "string" }
      - { label: "Maybe", name: "maybe", widget: "string" }
      - { label: "Not Going", name: "notGoing", widget: "string" }
      - { label: "Success - Title", name: "successTitle", widget: "string" }
      - { label: "Success - Sub Title", name: "successSubTitle", widget: "string" }
      - { label: "Success - Button Text", name: "successButtonText", widget: "string" }
  
  - name: "finalPhrase"
    label: "Final Phrase"
    folder: "src/info/finalPhrase"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "finalPhrase",
        }
      - { label: "Title", name: "title", widget: "string" }